[general]
import=[
    
]


[font]
size=12.0

[font.normal]
family="Fira Code"
style="Normal"

[font.bold]
family="Fira Code"
style="Bold"

[font.italic]
family="Fira Code"
style="Italic"

[font.bold_italic]
family="Fira Code"
style="Bold Italic"

[window]
opacity=0.9
blur=true

[window.padding]
x=8
y=8

[selection]
save_to_clipboard=true

[colors.primary]
foreground="#ffffff"
background="#000000"

[colors.normal]
black=  "#000000"
red=    "#ff0000"
green=  "#00ff00"
yellow= "#ffff00"
blue=   "#0000ff"
magenta="#ff00ff"
cyan=   "#00ffff"
white=  "#ffffff"

[colors.dim]
black=  "#000000"
red=    "#800000"
green=  "#008000"
yellow= "#808000"
blue=   "#000080"
magenta="#800080"
cyan=   "#008080"
white=  "#808080"

